# Generated by Django 4.2.2 on 2023-06-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_en', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
