# Generated by Django 4.2.2 on 2023-06-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_en', '0002_university_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='wikipedia_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
