# Generated by Django 4.2.2 on 2023-06-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_en', '0003_university_wikipedia_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='wikipedia_link',
            new_name='official_link',
        ),
    ]
