# Generated by Django 4.2.2 on 2023-06-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_en', '0004_rename_wikipedia_link_university_official_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.TextField(max_length=1024)),
                ('subject', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('second_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
