# Generated by Django 4.2.2 on 2023-06-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_en', '0005_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
