# Generated by Django 4.2.2 on 2023-06-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_en', '0007_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='profile_photo/')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('telephone_number', models.CharField(max_length=255)),
                ('extra_telephone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('extra_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link9', models.URLField(blank=True, null=True)),
                ('grade9', models.ImageField(blank=True, null=True, upload_to='certificates/school_certificates')),
                ('link11', models.URLField(blank=True, null=True)),
                ('grade11', models.ImageField(blank=True, null=True, upload_to='certificates/school_certificates')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s_certificates', to='main_en.account')),
            ],
            options={
                'verbose_name': 'School Certificate',
                'verbose_name_plural': 'School Certificates',
            },
        ),
        migrations.CreateModel(
            name='MainCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ielts', models.FileField(blank=True, null=True, upload_to='certificates/main_certificates')),
                ('toefl', models.FileField(blank=True, null=True, upload_to='certificates/main_certificates')),
                ('cefr', models.FileField(blank=True, null=True, upload_to='certificates/main_certificates')),
                ('sat', models.FileField(blank=True, null=True, upload_to='certificates/main_certificates')),
                ('gmat', models.FileField(blank=True, null=True, upload_to='certificates/main_certificates')),
                ('dtm', models.FileField(blank=True, null=True, upload_to='certificates/main_certificates')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='m_certificates', to='main_en.account')),
            ],
            options={
                'verbose_name': 'Main Certificate',
                'verbose_name_plural': 'Main Certificates',
            },
        ),
        migrations.CreateModel(
            name='ExtraCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(max_length=255)),
                ('certificate_image', models.ImageField(upload_to='certificates/extra_certificates')),
                ('certificate_description', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_certificates', to='main_en.account')),
            ],
            options={
                'verbose_name': 'Extra Certificate',
                'verbose_name_plural': 'Extra Certificates',
            },
        ),
    ]
